### ISSUE TITLE
Issue: Specify if inequality measures are pre- or post-taxes and transfers

### ISSUE THREAD

**Issue by MaxGhenis** [owid/poverty-data#11]
I arrived at this repo after trying to determine whether the Gini index in this chart is before or after taxes and transfers: https://ourworldindata.org/grapher/gdp-per-capita-vs-economic-inequality?country=GBR~USA

I couldn't find it, so if you could let me know I'd appreciate it. But more broadly, as a huge OWID fan I'd love to see specifying this become the norm. As the OWID chart I probably cite most shows ([below](https://ourworldindata.org/income-inequality)), it matters a great deal!

Thanks for all your work.
![inequality-of-incomes-before-and-after-taxes-and-transfers](https://user-images.githubusercontent.com/6076111/197119912-eb1dd452-60dc-4503-a6a0-062459ce20b7.png)

**Comment by paarriagadap** [comment]
Hello @MaxGhenis! Thanks for your comment, it is very relevant to make the distinction. We are trying to solve what's the best way to express this because data from the World Bank PIP comes from income and expenditure surveys. WB's goal is to have disposable income after transfers and taxes and consumption aggregates include purchased, own-produced, exchanged, and gifted food and non-food items (for example clothing, housing—including imputed rent—and the use value of durable consumer goods), as you can see [here](https://worldbank.github.io/PIP-Methodology/welfareaggregate.html#incomeorconsumption):
![image](https://user-images.githubusercontent.com/63430031/197150451-14030779-3d53-4130-a4af-3ab9b1ab9f36.png)

After the publication of the [poverty entry](https://ourworldindata.org/explorers/poverty-explorer), we will soon be presenting the inequality indices this platform provides, having the considerations of the last paragraph in mind. The same for all the charts currently available. And we are also starting a major update on inequality data, with other sources that explicitly have pre and post-tax data.

**Comment by paarriagadap** [comment]
Hello, @MaxGhenis! We have recently updated our [Economic Inequality page](https://ourworldindata.org/economic-inequality), where we include the type of income for each of our sources:

- World Bank data relates to either income after taxes and benefits or consumption, depending on the country and year.
- World Inequality Database relates to income before and after taxes and benefits. Income before taxes is also after the payment of public and private pensions.
- Luxembourg Income Study data relates to income before and after taxes and benefits, with per capita and equivalized income.

Please take a look at the new page and also at [this more in-depth article](https://ourworldindata.org/owid-data-collection-inequality-and-poverty), where we compare poverty and inequality indicators from these three sources.
